#+HUGO_BASE_DIR: ./
#+options: author:nil
#+MACRO: marginnote @@html:{{<marginnote>}}$1{{</marginnote>}}@@
#+MACRO: sidenote @@html:{{<sidenote>}}$1{{</sidenote>}}@@

* Posts
** First                                                              :meta:
:PROPERTIES:
:EXPORT_FILE_NAME: first
:EXPORT_DATE: 2023-10-12
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :meta true :math false
:END:
#+begin_description
Yeah... I'll have some stuff on here soon enough.
#+end_description

This is the first post, Just to get something up on this site.

* About
:PROPERTIES:
:EXPORT_FILE_NAME: About
:EXPORT_HUGO_SECTION: /
:EXPORT_HUGO_CUSTOM_FRONT_MATTER: :math false 
:END:

I am a freelance iOS and macOS developer in London. This is my personal, rather than a technical blog.

I've been publishing to this domain since 2009, but it's been a mix of personal and technical posts. The mix of the two has bothered me for a while and prevented me from posting as much as I would like to.

There is a concept in called [[https://www.emacswiki.org/emacs/DotEmacsBankruptcy][Dot Emacs Bankruptcy]]{{{sidenote(I know this because I've had to rewrite my .emacs.d file a couple of times.)}}} where your work has gotten so large and crufty it just makes sense to start again. That's what I am doing here. I'm going to be moving my technical posts{{{sidenote(The ones that aren't outdated\, or embarrassing)}}} to a new site{{{sidenote([https://abizern.dev](https://abizern.dev))}}} and keeping this for everything else.

** Site Comments
There are no comments on this site. Rather - there are no unmoderated comments on this site. I used to have a Wordpress blog with comments, but the signal got drowned out in the noise. Feel free to email me instead; I might even edit my posts to take account of feedback.

** Contact
Feel{{{marginnote(Looks odd\, but this way I know the contact is coming from this site)}}} free to contact me at [[mailto://ayes-leanest-0a@icloud.com][ayes-leanest-0a@icloud.com]].

I can be found on various places online with the username of =abizern=.

I'm not on Facebook. It started off as an exercise to see how long I'd manage without it, and I haven't found a need to create an account yet.

** GPG Key
Key ID: =7E2C07666BEEED1C=

Key Signature: =CF1C 8FE5 A508 0E70 4BCB  97DE 7E2C 0766 6BEE ED1C=

Key: Available on a keyserver near you, or you can [[/res/GPGKey.asc][download it]].